include("${CMAKE_SOURCE_DIR}/cmake/BundleEmbedCommon.cmake")

set(TGDB_BUNDLED_CACHE_DIR "${CMAKE_SOURCE_DIR}/third_party/bundled/cache")
set(TGDB_BUNDLED_GEN_DIR "${CMAKE_BINARY_DIR}/generated/bundled")
file(MAKE_DIRECTORY "${TGDB_BUNDLED_CACHE_DIR}")
file(MAKE_DIRECTORY "${TGDB_BUNDLED_GEN_DIR}")

set(TGDB_NODE_TAR_NAME "node-v${TGDB_NODE_VERSION}-linux-x64.tar.xz")
set(TGDB_NODE_URL "https://nodejs.org/dist/v${TGDB_NODE_VERSION}/${TGDB_NODE_TAR_NAME}")
set(TGDB_NODE_TAR_PATH "${TGDB_BUNDLED_CACHE_DIR}/${TGDB_NODE_TAR_NAME}")

set(TGDB_TYPESCRIPT_LS_STAGING_DIR "${TGDB_BUNDLED_GEN_DIR}/typescript_ls_staging")
set(TGDB_TYPESCRIPT_LS_PAYLOAD_DIR "${TGDB_BUNDLED_GEN_DIR}/typescript_ls_payload")
set(TGDB_TYPESCRIPT_LS_TAR_PATH "${TGDB_BUNDLED_GEN_DIR}/typescript_ls_blob.tar")
set(TGDB_TYPESCRIPT_LS_ZST_PATH "${TGDB_BUNDLED_GEN_DIR}/typescript_ls_blob.zst")
set(TGDB_TYPESCRIPT_LS_BLOB_OBJ "${TGDB_BUNDLED_GEN_DIR}/typescript_ls_blob.o")
set(TGDB_TYPESCRIPT_LS_MANIFEST_HPP
    "${TGDB_BUNDLED_GEN_DIR}/bundled_typescript_ls_manifest.hpp")

foreach(_tool objcopy zstd sha256sum npm)
  find_program(_tgdb_ts_${_tool} ${_tool})
  if(NOT _tgdb_ts_${_tool})
    message(FATAL_ERROR "TGDB_BUNDLE_TSSERVER requires '${_tool}'")
  endif()
endforeach()

set(TGDB_PREPARE_TYPESCRIPT_LS_SCRIPT
    "${CMAKE_SOURCE_DIR}/cmake/prepare_typescript_ls_bundle.sh")

add_custom_command(
  OUTPUT "${TGDB_TYPESCRIPT_LS_ZST_PATH}" "${TGDB_TYPESCRIPT_LS_MANIFEST_HPP}"
         "${TGDB_TYPESCRIPT_LS_BLOB_OBJ}"
  COMMAND "${CMAKE_COMMAND}" -E rm -rf
          "${TGDB_TYPESCRIPT_LS_STAGING_DIR}" "${TGDB_TYPESCRIPT_LS_PAYLOAD_DIR}"
  COMMAND "${CMAKE_COMMAND}" -E env
          TGDB_TYPESCRIPT_LS_VERSION="${TGDB_TYPESCRIPT_LS_VERSION}"
          TGDB_TYPESCRIPT_LS_NPM_VERSION="${TGDB_TYPESCRIPT_LS_NPM_VERSION}"
          TGDB_TYPESCRIPT_VERSION="${TGDB_TYPESCRIPT_VERSION}"
          TGDB_NODE_URL="${TGDB_NODE_URL}"
          TGDB_NODE_TAR_PATH="${TGDB_NODE_TAR_PATH}"
          TGDB_TYPESCRIPT_LS_STAGING_DIR="${TGDB_TYPESCRIPT_LS_STAGING_DIR}"
          TGDB_TYPESCRIPT_LS_PAYLOAD_DIR="${TGDB_TYPESCRIPT_LS_PAYLOAD_DIR}"
          TGDB_TYPESCRIPT_LS_TAR_PATH="${TGDB_TYPESCRIPT_LS_TAR_PATH}"
          TGDB_TYPESCRIPT_LS_ZST_PATH="${TGDB_TYPESCRIPT_LS_ZST_PATH}"
          TGDB_TYPESCRIPT_LS_MANIFEST_HPP="${TGDB_TYPESCRIPT_LS_MANIFEST_HPP}"
          TGDB_TYPESCRIPT_LS_BLOB_OBJ="${TGDB_TYPESCRIPT_LS_BLOB_OBJ}"
          bash "${TGDB_PREPARE_TYPESCRIPT_LS_SCRIPT}"
  DEPENDS "${TGDB_PREPARE_TYPESCRIPT_LS_SCRIPT}"
  COMMENT "Preparing embedded typescript-language-server ${TGDB_TYPESCRIPT_LS_VERSION}"
  VERBATIM)

add_custom_target(tgdb_typescript_ls_bundle DEPENDS
  "${TGDB_TYPESCRIPT_LS_ZST_PATH}" "${TGDB_TYPESCRIPT_LS_MANIFEST_HPP}"
  "${TGDB_TYPESCRIPT_LS_BLOB_OBJ}")

tgdb_link_embedded_blob(tgdb "${TGDB_TYPESCRIPT_LS_BLOB_OBJ}" TGDB_HAS_BUNDLED_TSSERVER
  TGDB_DEFAULT_FORCE_BUNDLED_TSSERVER "${TGDB_FORCE_BUNDLED_TSSERVER}")
add_dependencies(tgdb tgdb_typescript_ls_bundle)
