set(TUIDE_BUNDLED_CACHE_DIR "${CMAKE_SOURCE_DIR}/third_party/bundled/cache")
set(TUIDE_BUNDLED_GEN_DIR "${CMAKE_BINARY_DIR}/generated/bundled")

file(MAKE_DIRECTORY "${TUIDE_BUNDLED_CACHE_DIR}")
file(MAKE_DIRECTORY "${TUIDE_BUNDLED_GEN_DIR}")

set(TUIDE_PYTHON_STANDALONE_TAR_NAME
    "cpython-${TUIDE_PYTHON_STANDALONE_VERSION}+${TUIDE_PYTHON_STANDALONE_TAG}-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz")
set(TUIDE_PYTHON_STANDALONE_URL
    "https://github.com/astral-sh/python-build-standalone/releases/download/${TUIDE_PYTHON_STANDALONE_TAG}/${TUIDE_PYTHON_STANDALONE_TAR_NAME}")
set(TUIDE_PYTHON_STANDALONE_TAR_PATH
    "${TUIDE_BUNDLED_CACHE_DIR}/${TUIDE_PYTHON_STANDALONE_TAR_NAME}")

set(TUIDE_PYTHON_TOOLS_STAGING_DIR "${TUIDE_BUNDLED_GEN_DIR}/python_tools_staging")
set(TUIDE_PYTHON_TOOLS_PAYLOAD_DIR "${TUIDE_BUNDLED_GEN_DIR}/python_tools_payload")
set(TUIDE_PYTHON_TOOLS_TAR_PATH "${TUIDE_BUNDLED_GEN_DIR}/python_tools_blob.tar")
set(TUIDE_PYTHON_TOOLS_ZST_PATH "${TUIDE_BUNDLED_GEN_DIR}/python_tools_blob.zst")
set(TUIDE_PYTHON_TOOLS_MANIFEST_PATH "${TUIDE_BUNDLED_GEN_DIR}/python_tools_manifest.json")
set(TUIDE_PYTHON_TOOLS_BLOB_OBJ "${TUIDE_BUNDLED_GEN_DIR}/python_tools_blob.o")
set(TUIDE_PYTHON_TOOLS_MANIFEST_HPP "${TUIDE_BUNDLED_GEN_DIR}/bundled_python_tools_manifest.hpp")

find_program(TUIDE_OBJCOPY objcopy)
find_program(TUIDE_ZSTD zstd)
find_program(TUIDE_SHA256SUM sha256sum)
find_program(TUIDE_CURL curl)
find_program(TUIDE_WGET wget)

foreach(_tool TUIDE_OBJCOPY TUIDE_ZSTD TUIDE_SHA256SUM)
  if(NOT ${_tool})
    message(FATAL_ERROR "TUIDE_BUNDLE_PYTHON_TOOLS requires '${_tool}' in PATH")
  endif()
endforeach()

if(NOT TUIDE_CURL AND NOT TUIDE_WGET)
  message(FATAL_ERROR "TUIDE_BUNDLE_PYTHON_TOOLS requires curl or wget")
endif()

set(TUIDE_PREPARE_PYTHON_TOOLS_SCRIPT
    "${CMAKE_SOURCE_DIR}/cmake/prepare_python_tools_bundle.sh")

add_custom_command(
  OUTPUT "${TUIDE_PYTHON_TOOLS_ZST_PATH}" "${TUIDE_PYTHON_TOOLS_MANIFEST_PATH}"
         "${TUIDE_PYTHON_TOOLS_MANIFEST_HPP}" "${TUIDE_PYTHON_TOOLS_BLOB_OBJ}"
  COMMAND "${CMAKE_COMMAND}" -E rm -rf
          "${TUIDE_PYTHON_TOOLS_STAGING_DIR}" "${TUIDE_PYTHON_TOOLS_PAYLOAD_DIR}"
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${TUIDE_PYTHON_TOOLS_STAGING_DIR}"
  COMMAND "${CMAKE_COMMAND}" -E env
          TUIDE_PYTHON_TOOLS_VERSION="${TUIDE_PYTHON_TOOLS_VERSION}"
          TUIDE_BASEDPYRIGHT_VERSION="${TUIDE_BASEDPYRIGHT_VERSION}"
          TUIDE_DEBUGPY_VERSION="${TUIDE_DEBUGPY_VERSION}"
          TUIDE_PYTHON_STANDALONE_URL="${TUIDE_PYTHON_STANDALONE_URL}"
          TUIDE_PYTHON_STANDALONE_TAR_PATH="${TUIDE_PYTHON_STANDALONE_TAR_PATH}"
          TUIDE_PYTHON_TOOLS_STAGING_DIR="${TUIDE_PYTHON_TOOLS_STAGING_DIR}"
          TUIDE_PYTHON_TOOLS_PAYLOAD_DIR="${TUIDE_PYTHON_TOOLS_PAYLOAD_DIR}"
          TUIDE_PYTHON_TOOLS_TAR_PATH="${TUIDE_PYTHON_TOOLS_TAR_PATH}"
          TUIDE_PYTHON_TOOLS_ZST_PATH="${TUIDE_PYTHON_TOOLS_ZST_PATH}"
          TUIDE_PYTHON_TOOLS_MANIFEST_PATH="${TUIDE_PYTHON_TOOLS_MANIFEST_PATH}"
          TUIDE_PYTHON_TOOLS_MANIFEST_HPP="${TUIDE_PYTHON_TOOLS_MANIFEST_HPP}"
          TUIDE_PYTHON_TOOLS_BLOB_OBJ="${TUIDE_PYTHON_TOOLS_BLOB_OBJ}"
          bash "${TUIDE_PREPARE_PYTHON_TOOLS_SCRIPT}"
  DEPENDS "${TUIDE_PREPARE_PYTHON_TOOLS_SCRIPT}"
  COMMENT "Preparing embedded CPython+basedpyright+debugpy (full)"
  VERBATIM)

add_custom_target(tuide_python_tools_bundle DEPENDS
                  "${TUIDE_PYTHON_TOOLS_ZST_PATH}" "${TUIDE_PYTHON_TOOLS_MANIFEST_HPP}"
                  "${TUIDE_PYTHON_TOOLS_BLOB_OBJ}")

include("${CMAKE_SOURCE_DIR}/cmake/BundleZstd.cmake")

target_sources(tuide PRIVATE "${TUIDE_PYTHON_TOOLS_BLOB_OBJ}")
target_include_directories(tuide PRIVATE "${TUIDE_BUNDLED_GEN_DIR}")
target_compile_definitions(tuide PRIVATE TUIDE_HAS_BUNDLED_PYTHON_TOOLS=1)
if(TUIDE_FORCE_BUNDLED_PYTHON_TOOLS)
  target_compile_definitions(tuide PRIVATE TUIDE_DEFAULT_FORCE_BUNDLED_PYTHON_TOOLS=1)
endif()
target_link_libraries(tuide PRIVATE libzstd_static)
add_dependencies(tuide tuide_python_tools_bundle)
