set(TUIDE_BUNDLED_CACHE_DIR "${CMAKE_SOURCE_DIR}/third_party/bundled/cache")
set(TUIDE_BUNDLED_GEN_DIR "${CMAKE_BINARY_DIR}/generated/bundled")
file(MAKE_DIRECTORY "${TUIDE_BUNDLED_CACHE_DIR}")
file(MAKE_DIRECTORY "${TUIDE_BUNDLED_GEN_DIR}")

set(TUIDE_TEXLAB_TAR_NAME "texlab-x86_64-linux.tar.gz")
set(TUIDE_TEXLAB_URL
    "https://github.com/latex-lsp/texlab/releases/download/v${TUIDE_TEXLAB_VERSION}/${TUIDE_TEXLAB_TAR_NAME}")
set(TUIDE_TEXLAB_TAR_PATH "${TUIDE_BUNDLED_CACHE_DIR}/${TUIDE_TEXLAB_TAR_NAME}")
set(TUIDE_CHKTEX_DEB_NAME "chktex_${TUIDE_CHKTEX_VERSION}_amd64.deb")
set(TUIDE_CHKTEX_DEB_URL
    "https://deb.debian.org/debian/pool/main/c/chktex/${TUIDE_CHKTEX_DEB_NAME}")
set(TUIDE_CHKTEX_DEB_PATH "${TUIDE_BUNDLED_CACHE_DIR}/${TUIDE_CHKTEX_DEB_NAME}")
set(TUIDE_PCRE2_POSIX_DEB_NAME "libpcre2-posix3_${TUIDE_PCRE2_VERSION}_amd64.deb")
set(TUIDE_PCRE2_POSIX_DEB_URL
    "https://deb.debian.org/debian/pool/main/p/pcre2/${TUIDE_PCRE2_POSIX_DEB_NAME}")
set(TUIDE_PCRE2_POSIX_DEB_PATH "${TUIDE_BUNDLED_CACHE_DIR}/${TUIDE_PCRE2_POSIX_DEB_NAME}")
set(TUIDE_PCRE2_8_DEB_NAME "libpcre2-8-0_${TUIDE_PCRE2_VERSION}_amd64.deb")
set(TUIDE_PCRE2_8_DEB_URL
    "https://deb.debian.org/debian/pool/main/p/pcre2/${TUIDE_PCRE2_8_DEB_NAME}")
set(TUIDE_PCRE2_8_DEB_PATH "${TUIDE_BUNDLED_CACHE_DIR}/${TUIDE_PCRE2_8_DEB_NAME}")
set(TUIDE_TEXLAB_STAGING_DIR "${TUIDE_BUNDLED_GEN_DIR}/texlab_staging")
set(TUIDE_TEXLAB_PAYLOAD_DIR "${TUIDE_BUNDLED_GEN_DIR}/texlab_payload")
set(TUIDE_TEXLAB_TAR_PATH_OUT "${TUIDE_BUNDLED_GEN_DIR}/texlab_blob.tar")
set(TUIDE_TEXLAB_ZST_PATH "${TUIDE_BUNDLED_GEN_DIR}/texlab_blob.zst")
set(TUIDE_TEXLAB_MANIFEST_PATH "${TUIDE_BUNDLED_GEN_DIR}/texlab_manifest.json")
set(TUIDE_TEXLAB_BLOB_OBJ "${TUIDE_BUNDLED_GEN_DIR}/texlab_blob.o")
set(TUIDE_TEXLAB_MANIFEST_HPP "${TUIDE_BUNDLED_GEN_DIR}/bundled_texlab_manifest.hpp")

find_program(TUIDE_OBJCOPY objcopy)
find_program(TUIDE_ZSTD zstd)
find_program(TUIDE_SHA256SUM sha256sum)
foreach(_tool TUIDE_OBJCOPY TUIDE_ZSTD TUIDE_SHA256SUM)
  if(NOT ${_tool})
    message(FATAL_ERROR "TUIDE_BUNDLE_TEXLAB requires '${_tool}'")
  endif()
endforeach()

set(TUIDE_PREPARE_TEXLAB_SCRIPT "${CMAKE_SOURCE_DIR}/cmake/prepare_texlab_bundle.sh")

add_custom_command(
  OUTPUT "${TUIDE_TEXLAB_ZST_PATH}" "${TUIDE_TEXLAB_MANIFEST_HPP}" "${TUIDE_TEXLAB_BLOB_OBJ}"
  COMMAND "${CMAKE_COMMAND}" -E rm -rf "${TUIDE_TEXLAB_STAGING_DIR}" "${TUIDE_TEXLAB_PAYLOAD_DIR}"
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${TUIDE_TEXLAB_STAGING_DIR}"
  COMMAND "${CMAKE_COMMAND}" -E env
          TUIDE_TEXLAB_VERSION="${TUIDE_TEXLAB_VERSION}"
          TUIDE_TEXLAB_URL="${TUIDE_TEXLAB_URL}"
          TUIDE_TEXLAB_TAR_PATH="${TUIDE_TEXLAB_TAR_PATH}"
          TUIDE_CHKTEX_VERSION="${TUIDE_CHKTEX_VERSION}"
          TUIDE_CHKTEX_DEB_NAME="${TUIDE_CHKTEX_DEB_NAME}"
          TUIDE_CHKTEX_DEB_URL="${TUIDE_CHKTEX_DEB_URL}"
          TUIDE_CHKTEX_DEB_PATH="${TUIDE_CHKTEX_DEB_PATH}"
          TUIDE_PCRE2_VERSION="${TUIDE_PCRE2_VERSION}"
          TUIDE_PCRE2_POSIX_DEB_NAME="${TUIDE_PCRE2_POSIX_DEB_NAME}"
          TUIDE_PCRE2_POSIX_DEB_URL="${TUIDE_PCRE2_POSIX_DEB_URL}"
          TUIDE_PCRE2_POSIX_DEB_PATH="${TUIDE_PCRE2_POSIX_DEB_PATH}"
          TUIDE_PCRE2_8_DEB_NAME="${TUIDE_PCRE2_8_DEB_NAME}"
          TUIDE_PCRE2_8_DEB_URL="${TUIDE_PCRE2_8_DEB_URL}"
          TUIDE_PCRE2_8_DEB_PATH="${TUIDE_PCRE2_8_DEB_PATH}"
          TUIDE_TEXLAB_STAGING_DIR="${TUIDE_TEXLAB_STAGING_DIR}"
          TUIDE_TEXLAB_PAYLOAD_DIR="${TUIDE_TEXLAB_PAYLOAD_DIR}"
          TUIDE_TEXLAB_TAR_PATH_OUT="${TUIDE_TEXLAB_TAR_PATH_OUT}"
          TUIDE_TEXLAB_ZST_PATH="${TUIDE_TEXLAB_ZST_PATH}"
          TUIDE_TEXLAB_MANIFEST_PATH="${TUIDE_TEXLAB_MANIFEST_PATH}"
          TUIDE_TEXLAB_MANIFEST_HPP="${TUIDE_TEXLAB_MANIFEST_HPP}"
          TUIDE_TEXLAB_BLOB_OBJ="${TUIDE_TEXLAB_BLOB_OBJ}"
          bash "${TUIDE_PREPARE_TEXLAB_SCRIPT}"
  DEPENDS "${TUIDE_PREPARE_TEXLAB_SCRIPT}"
  COMMENT "Preparing embedded TexLab ${TUIDE_TEXLAB_VERSION} + ChkTeX ${TUIDE_CHKTEX_VERSION}"
  VERBATIM)

add_custom_target(tuide_texlab_bundle DEPENDS
  "${TUIDE_TEXLAB_ZST_PATH}" "${TUIDE_TEXLAB_MANIFEST_HPP}" "${TUIDE_TEXLAB_BLOB_OBJ}")

include("${CMAKE_SOURCE_DIR}/cmake/BundleZstd.cmake")
target_sources(tuide PRIVATE "${TUIDE_TEXLAB_BLOB_OBJ}")
target_include_directories(tuide PRIVATE "${TUIDE_BUNDLED_GEN_DIR}")
target_compile_definitions(tuide PRIVATE TUIDE_HAS_BUNDLED_TEXLAB=1)
if(TUIDE_FORCE_BUNDLED_TEXLAB)
  target_compile_definitions(tuide PRIVATE TUIDE_DEFAULT_FORCE_BUNDLED_TEXLAB=1)
endif()
target_link_libraries(tuide PRIVATE libzstd_static)
add_dependencies(tuide tuide_texlab_bundle)
